// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.com.paisesmodel.dominio;

import co.com.paisesmodel.dominio.Departamentos;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Departamentos_Roo_Configurable {
    
    declare @type: Departamentos: @Configurable;
    
}
